### ISSUE TITLE
get 3end_siteCoordinates for mouse

### ISSUE THREAD

**Issue by Yue2308** [churchmanlab/MiMB2019NETseq#1]
Hi,

This pipeline requires a file called : "hg38_GENCODE_V24_ex_in_3end_siteCoordinates_1based.txt"
I tried to create the same file for mouse but I was confused by how to get the coordinates. Could you please share the code for generating this file?

Thank you!

**Comment by ri23** [comment]
We got this through the UCSC Table browser: https://genome.ucsc.edu/cgi-bin/hgTables

**Comment by Yue2308** [comment]
Hi,
Thanks for your reply.

When I looked at the "hg38_GENCODE_V24_ex_in_3end_siteCoordinates_1based.txt" coordinates in UCSC genome broswer and compared them with spliced ESTs, not all 3'end of introns were included in this file. Did you perform some filtration for the transcripts?

Yue

**Comment by ri23** [comment]
I have now updated the readme with further instructions on how to get the right UCSC table file and added a script to generate the `hg38_GENCODE_V24_ex_in_3end_siteCoordinates_1based.txt` from that UCSC table file. This should be sufficient to adjust it for mouse by using a mouse UCSC table file as input.

**Comment by Yue2308** [comment]
Thank you! The problem was solved.
